# Site settings
title: Matthew Wilson
email: 1matwils@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes and experiences as a web application developer 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mwils.github.io/" # the base hostname & protocol for your site
github_username:  mwils

# Build settings
markdown: kramdown
